version: '3.9'

services:
  database: 
    container_name: postgres_db
    image: 'postgres'
    ports: 
      - '5433:5432'
    env_file:
      - .env
# version: '3'
# services:
#   db:
#     image: postgres
#     restart: always
#     environment:
#       POSTGRES_PASSWORD: 752381
#     volumes:
#       - ./data:/var/lib/postgresql/data
#     ports:
#       - "5433:5432"
