version: '3.9'

services:
  database: 
    container_name: postgres_db
    image: 'postgres'
    ports: 
      - '5433:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  test_database:
    container_name: postgres_test_db
    image: 'postgres'
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_TEST_USER}
      - POSTGRES_PASSWORD=${POSTGRES_TEST_PASSWORD}
      - POSTGRES_DB=${POSTGRES_TEST_DB}
  


      
  #   image: postgres
  #   environment: 
  #     - POSTGRES_DB=test_database
  #     - POSTGRES_USER=derPatecopatest
  #     - POSTGRES_PASSWORD=test
  #   ports:
  #     - '5434:5432'
 
   




