version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - '5433:5432'
    env_file:
      - .env
    volumes:
      - 'postgres:/var/lib/postgresql/data'

volumes:
  postgres:
# version: '3'
# services:
#   db:
#     image: postgres
#     restart: always
#     environment:
#       POSTGRES_PASSWORD: 752381
#     volumes:
#       - ./data:/var/lib/postgresql/data
#     ports:
#       - "5433:5432"
